/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ThriftTest_constants.h"

namespace Test {

const ThriftTestConstants g_ThriftTest_constants;

ThriftTestConstants::ThriftTestConstants() {
}

} // namespace

