/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ThriftTest_CONSTANTS_H
#define ThriftTest_CONSTANTS_H

#include "ThriftTest_types.h"

namespace Test {

class ThriftTestConstants {
 public:
  ThriftTestConstants();

};

extern const ThriftTestConstants g_ThriftTest_constants;

} // namespace

#endif
